{
  "repository": {
    "name": "apache/calcite",
    "githubId": 21193524,
    "url": "https://github.com/apache/calcite",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": true,
    "pullRequestId": 647
  },
  "builds": {
    "buggyBuild": {
      "id": 406570899,
      "url": "http://travis-ci.org/apache/calcite/builds/406570899",
      "date": "Jul 21, 2018 1:42:09 PM"
    }
  },
  "tests": {
    "failingModule": "/root/workspace/apache/calcite/406570899/plus",
    "overallMetrics": {
      "numberRunning": 5146,
      "numberPassing": 5145,
      "numberFailing": 1,
      "numberErroring": 0,
      "numberSkipping": 158,
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 1
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "org.apache.calcite.chinook.EndToEndTest",
        "numberRunning": 5,
        "numberPassing": 4,
        "numberFailing": 1,
        "numberErroring": 0,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "org.apache.calcite.chinook.EndToEndTest",
        "testMethod": "test[2: quidem(sql/access_as_specificuser_test.iq)]",
        "failureName": "java.lang.AssertionError",
        "detail": "Files differ: /root/workspace/apache/calcite/406570899/plus/target/surefire/sql/access_as_specificuser_test.iq /root/workspace/apache/calcite/406570899/plus/target/test-classes/sql/access_as_specificuser_test.iq\n21,91c21,91\n\u003c  java.sql.SQLException: Error while executing SQL \"SELECT COUNT(*) as C1 FROM chinook.album\": From line 1, column 28 to line 1, column 40: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003c   at org.apache.calcite.avatica.Helper.createException(Helper.java:56)\n\u003c   at org.apache.calcite.avatica.Helper.createException(Helper.java:41)\n\u003c   at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:163)\n\u003c   at org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:227)\n\u003c   at net.hydromatic.quidem.Quidem.checkResult(Quidem.java:322)\n\u003c   at net.hydromatic.quidem.Quidem.access$2800(Quidem.java:54)\n\u003c   at net.hydromatic.quidem.Quidem$ContextImpl.checkResult(Quidem.java:1747)\n\u003c   at net.hydromatic.quidem.Quidem$CheckResultCommand.execute(Quidem.java:1078)\n\u003c   at net.hydromatic.quidem.Quidem$CompositeCommand.execute(Quidem.java:1548)\n\u003c   at net.hydromatic.quidem.Quidem.execute(Quidem.java:216)\n\u003c   at org.apache.calcite.test.QuidemTest.checkRun(QuidemTest.java:175)\n\u003c   at org.apache.calcite.test.QuidemTest.test(QuidemTest.java:212)\n\u003c   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\u003c   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\u003c   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\u003c   at java.lang.reflect.Method.invoke(Method.java:498)\n\u003c   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\u003c   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\u003c   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\u003c   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\u003c   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\u003c   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\u003c   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\u003c   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\u003c   at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)\n\u003c   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\u003c   at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\u003c   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\u003c   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\u003c   at java.lang.Thread.run(Thread.java:748)\n\u003c  Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 28 to line 1, column 40: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003c   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\u003c   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\u003c   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\u003c   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\u003c   at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)\n\u003c   at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783)\n\u003c   at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4779)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateAccess(SqlValidatorImpl.java:4612)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:953)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3027)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3012)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3271)\n\u003c   at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)\n\u003c   at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:965)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:944)\n\u003c   at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:919)\n\u003c   at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:629)\n\u003c   at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:552)\n\u003c   at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:264)\n\u003c   at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:230)\n\u003c   at org.apache.calcite.prepare.CalcitePrepareImpl.prepare2_(CalcitePrepareImpl.java:773)\n\u003c   at org.apache.calcite.prepare.CalcitePrepareImpl.prepare_(CalcitePrepareImpl.java:638)\n\u003c   at org.apache.calcite.prepare.CalcitePrepareImpl.prepareSql(CalcitePrepareImpl.java:608)\n\u003c   at org.apache.calcite.jdbc.CalciteConnectionImpl.parseQuery(CalciteConnectionImpl.java:238)\n\u003c   at org.apache.calcite.jdbc.CalciteMetaImpl.prepareAndExecute(CalciteMetaImpl.java:550)\n\u003c   at org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:675)\n\u003c   at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)\n\u003c   ... 27 more\n\u003c  Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003c   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\u003c   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\u003c   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\u003c   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\u003c   at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)\n\u003c   at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)\n\u003c   ... 52 more\n---\n\u003e java.sql.SQLException: Error while executing SQL \"SELECT COUNT(*) as C1 FROM chinook.album\": From line 1, column 28 to line 1, column 40: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003e  at org.apache.calcite.avatica.Helper.createException(Helper.java:56)\n\u003e  at org.apache.calcite.avatica.Helper.createException(Helper.java:41)\n\u003e  at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:163)\n\u003e  at org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:227)\n\u003e  at net.hydromatic.quidem.Quidem.checkResult(Quidem.java:322)\n\u003e  at net.hydromatic.quidem.Quidem.access$2800(Quidem.java:54)\n\u003e  at net.hydromatic.quidem.Quidem$ContextImpl.checkResult(Quidem.java:1747)\n\u003e  at net.hydromatic.quidem.Quidem$CheckResultCommand.execute(Quidem.java:1078)\n\u003e  at net.hydromatic.quidem.Quidem$CompositeCommand.execute(Quidem.java:1548)\n\u003e  at net.hydromatic.quidem.Quidem.execute(Quidem.java:216)\n\u003e  at org.apache.calcite.test.QuidemTest.checkRun(QuidemTest.java:175)\n\u003e  at org.apache.calcite.test.QuidemTest.test(QuidemTest.java:212)\n\u003e  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\u003e  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\u003e  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\u003e  at java.lang.reflect.Method.invoke(Method.java:498)\n\u003e  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\u003e  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\u003e  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\u003e  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\u003e  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\u003e  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\u003e  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\u003e  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\u003e  at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)\n\u003e  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\u003e  at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\u003e  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\u003e  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\u003e  at java.lang.Thread.run(Thread.java:745)\n\u003e Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 28 to line 1, column 40: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003e  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\u003e  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\u003e  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\u003e  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\u003e  at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)\n\u003e  at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783)\n\u003e  at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4779)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateAccess(SqlValidatorImpl.java:4612)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:953)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3027)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3012)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3271)\n\u003e  at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)\n\u003e  at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:965)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:944)\n\u003e  at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:919)\n\u003e  at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:629)\n\u003e  at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:552)\n\u003e  at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:264)\n\u003e  at org.apache.calcite.prepare.Prepare.prepareSql(Prepare.java:230)\n\u003e  at org.apache.calcite.prepare.CalcitePrepareImpl.prepare2_(CalcitePrepareImpl.java:773)\n\u003e  at org.apache.calcite.prepare.CalcitePrepareImpl.prepare_(CalcitePrepareImpl.java:638)\n\u003e  at org.apache.calcite.prepare.CalcitePrepareImpl.prepareSql(CalcitePrepareImpl.java:608)\n\u003e  at org.apache.calcite.jdbc.CalciteConnectionImpl.parseQuery(CalciteConnectionImpl.java:238)\n\u003e  at org.apache.calcite.jdbc.CalciteMetaImpl.prepareAndExecute(CalciteMetaImpl.java:550)\n\u003e  at org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:675)\n\u003e  at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)\n\u003e  ... 27 more\n\u003e Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Not allowed to perform SELECT on [CHINOOK, ALBUM]\n\u003e  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\u003e  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\u003e  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\u003e  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\u003e  at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)\n\u003e  at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)\n\u003e  ... 52 more\n",
        "isError": false
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "apache/calcite",
      "branchName": "master",
      "sha": "62ba12edf69bae774b966132d8eaf1ab5125cfd4",
      "url": "http://github.com/apache/calcite/commit/62ba12edf69bae774b966132d8eaf1ab5125cfd4",
      "date": "Jul 21, 2018 1:13:20 PM"
    },
    "buggyBuildForkRepo": {
      "repoName": "ptrbojko/calcite",
      "branchName": "CALCITE-2194",
      "sha": "d31abb26da89578a72d21412865a8bbd2a270b31",
      "url": "https://github.com/ptrbojko/calcite/commit/d31abb26da89578a72d21412865a8bbd2a270b31",
      "date": "Jul 21, 2018 1:13:20 PM"
    },
    "buggyBuildBaseRepo": {
      "repoName": "apache/calcite",
      "branchName": "master",
      "sha": "dc69a4515198b5b0f980f6a77ca9c3d25a85c4f6",
      "url": "https://github.com/apache/calcite/commit/dc69a4515198b5b0f980f6a77ca9c3d25a85c4f6",
      "date": "Jul 21, 2018 1:11:17 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Jul 21, 2018 1:42:28 PM",
    "reproductionDateEnd": "Jul 21, 2018 1:58:05 PM",
    "totalDuration": 932,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 28,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          28
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 188,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          4,
          184
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 676,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          676
        ]
      }
    },
    "projectRootPomPath": "./workspace/apache/calcite/406570899/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "projectMetrics": {
    "numberModules": 19,
    "numberSourceFiles": 1518,
    "numberTestFiles": 211,
    "numberLibrariesFailingModule": 37
  },
  "type": "only_fail"
}