<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="fr.inria.astor.test.repair.QuixBugsRepairTest" time="59.582" tests="21" errors="20" skipped="1" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.121-b13"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="/root/workspace/SpoonLabs/astor/383218747"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="skip.gulp" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="findbugs.skip" value="true"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/root/workspace/SpoonLabs/astor/383218747"/>
    <property name="checkstyle.skip" value="true"/>
    <property name="java.runtime.version" value="1.8.0_121-8u121-b13-1~bpo8+1-b13"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="skip.npm" value="true"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="gpg.skip" value="true"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="cobertura.skip" value="true"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="license.skip" value="true"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="skip.bower" value="true"/>
    <property name="maven.repo.local" value="/root/./workspace/SpoonLabs/astor/383218747/.m2"/>
    <property name="os.version" value="3.10.0-862.2.3.el7.x86_64"/>
    <property name="user.home" value="/root"/>
    <property name="user.timezone" value="Europe/Paris"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="root"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.5.2.jar"/>
    <property name="skipITs" value="true"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -B -D enforcer.skip=true -D dependency-check.skip=true -D skipITs=true -D cobertura.skip=true -D maven.repo.local=/root/./workspace/SpoonLabs/astor/383218747/.m2 -D rat.skip=true -D findbugs.skip=true -D skip.bower=true -D gpg.skip=true -D checkstyle.skip=true -D skip.gulp=true -D license.skip=true -D skip.npm=true test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="dependency-check.skip" value="true"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_121"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="enforcer.skip" value="true"/>
    <property name="rat.skip" value="true"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="test_shortest_path_lengthsRepair_statement" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="4.996">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_shortest_path_lengthsRepair_statement(QuixBugsRepairTest.java:72)
</error>
    <system-out><![CDATA[[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:606) - command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  shortest_path_lengths  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/shortest_path_lengths  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  statement  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-shortest_path_lengths/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-shortest_path_lengths//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-shortest_path_lengths/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-shortest_path_lengths//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-shortest_path_lengths/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_shortest_path_lengthsRepair_statement(QuixBugsRepairTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_rpn_evalRepair_Cardumen" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.981">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_rpn_evalRepair_Cardumen(QuixBugsRepairTest.java:215)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  rpn_eval  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/rpn_eval  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_rpn_evalRepair_Cardumen(QuixBugsRepairTest.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_depth_first_searchRepair_statement" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="3.06">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_statement(QuixBugsRepairTest.java:89)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  depth_first_search  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/depth_first_search  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  statement  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_statement(QuixBugsRepairTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_next_permutationRepair_mutation" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.906">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_next_permutationRepair_mutation(QuixBugsRepairTest.java:143)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  next_permutation  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/next_permutation  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  mutation  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-next_permutation/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-next_permutation//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-next_permutation/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-next_permutation//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-next_permutation/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_next_permutationRepair_mutation(QuixBugsRepairTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_get_factorsRepair_cardumen" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.763">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_get_factorsRepair_cardumen(QuixBugsRepairTest.java:251)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  get_factors  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/get_factors  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-get_factors/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-get_factors//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-get_factors/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-get_factors//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-get_factors/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_get_factorsRepair_cardumen(QuixBugsRepairTest.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_mergesortRepair_mergesort" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.883">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_mergesortRepair_mergesort(QuixBugsRepairTest.java:269)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  mergesort  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/mergesort  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-mergesort/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-mergesort//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-mergesort/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-mergesort//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-mergesort/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_mergesortRepair_mergesort(QuixBugsRepairTest.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="ne_test_levenshteinRepair_cardumen1h" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.894">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_levenshteinRepair_cardumen1h(QuixBugsRepairTest.java:407)
</error>
    <system-out><![CDATA[command line arguments: [-customengine  fr.inria.astor.approaches.cardumholes.Cardumen1HApproach  -package  java_programs  -srcjavafolder  /src  -id  levenshtein  -scope  global  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  false  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/levenshtein  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  custom  -bintestfolder  /bin  -maxgen  2000]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default
Generators loaded [fr.inria.astor.approaches.tos.ingredients.processors.VariablePlaceholderGenerator@5140628b]
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_levenshteinRepair_cardumen1h(QuixBugsRepairTest.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_depth_first_searchRepair_jkali" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.916">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:178)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_jkali(QuixBugsRepairTest.java:125)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  depth_first_search  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/depth_first_search  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  jkali  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:178)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_jkali(QuixBugsRepairTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="testLISSpaces" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.855">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.testLISSpaces(QuixBugsRepairTest.java:345)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  lis  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/lis  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  statement  -bintestfolder  /bin  -maxgen  0]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar, /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.testLISSpaces(QuixBugsRepairTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="ne_test_hanoiRepair_cardumen" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.879">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_hanoiRepair_cardumen(QuixBugsRepairTest.java:466)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  hanoi  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/hanoi  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  1000]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-hanoi/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-hanoi//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-hanoi/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-hanoi//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-hanoi/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_hanoiRepair_cardumen(QuixBugsRepairTest.java:466)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_powersetRepair_tibra" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.794">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_powersetRepair_tibra(QuixBugsRepairTest.java:289)
</error>
    <system-out><![CDATA[command line arguments: [-customengine  fr.inria.astor.approaches.jgenprog.extension.TibraApproach  -package  java_programs  -srcjavafolder  /src  -id  powerset  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/powerset  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  custom  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-powerset/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-powerset//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-powerset/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-powerset//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-powerset/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_powersetRepair_tibra(QuixBugsRepairTest.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="testLISRepair_statement" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.978">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.testLISRepair_statement(QuixBugsRepairTest.java:327)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  lis  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/lis  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  statement  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar, /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.testLISRepair_statement(QuixBugsRepairTest.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_next_knapsackRepairMutation" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.794">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_next_knapsackRepairMutation(QuixBugsRepairTest.java:161)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  knapsack  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/knapsack  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  mutation  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-knapsack/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-knapsack//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-knapsack/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-knapsack//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-knapsack/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_next_knapsackRepairMutation(QuixBugsRepairTest.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="ne_test_hanoiRepair_cardumen1h" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="0">
    <skipped/>
  </testcase>
  <testcase name="ne_test_rpn_evalRepair_cardumen1h" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.777">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_rpn_evalRepair_cardumen1h(QuixBugsRepairTest.java:423)
</error>
    <system-out><![CDATA[command line arguments: [-customengine  fr.inria.astor.approaches.cardumholes.Cardumen1HApproach  -package  java_programs  -srcjavafolder  /src  -id  rpn_eval  -scope  global  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  false  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/rpn_eval  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  custom  -bintestfolder  /bin  -maxgen  20000]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default
Generators loaded [fr.inria.astor.approaches.tos.ingredients.processors.VariablePlaceholderGenerator@163135]
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-rpn_eval/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_rpn_evalRepair_cardumen1h(QuixBugsRepairTest.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_quicksortRepair_jkali" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.857">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:178)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_quicksortRepair_jkali(QuixBugsRepairTest.java:197)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  quicksort  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/quicksort  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  jkali  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:178)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_quicksortRepair_jkali(QuixBugsRepairTest.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="ne_test_depth_first_searchRepair_cardumen1h" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.743">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_depth_first_searchRepair_cardumen1h(QuixBugsRepairTest.java:385)
</error>
    <system-out><![CDATA[command line arguments: [-customengine  fr.inria.astor.approaches.cardumholes.Cardumen1HApproach  -package  java_programs  -srcjavafolder  /src  -id  depth_first_search  -scope  global  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  false  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/depth_first_search  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  custom  -bintestfolder  /bin  -maxgen  2000]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default
Generators loaded [fr.inria.astor.approaches.tos.ingredients.processors.VariablePlaceholderGenerator@1f1af930]
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.ne_test_depth_first_searchRepair_cardumen1h(QuixBugsRepairTest.java:385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_quicksortRepair_mutation" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.89">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_quicksortRepair_mutation(QuixBugsRepairTest.java:179)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  quicksort  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/quicksort  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  mutation  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-quicksort/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:180)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_quicksortRepair_mutation(QuixBugsRepairTest.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_levenshteinRepair_cardumen" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.851">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_levenshteinRepair_cardumen(QuixBugsRepairTest.java:233)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  levenshtein  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/levenshtein  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-levenshtein/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_levenshteinRepair_cardumen(QuixBugsRepairTest.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_depth_first_searchRepair_cardumen" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.876">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_cardumen(QuixBugsRepairTest.java:107)
</error>
    <system-out><![CDATA[command line arguments: [-package  java_programs  -srcjavafolder  /src  -id  depth_first_search  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/depth_first_search  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  cardumen  -bintestfolder  /bin  -maxgen  500]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search//bin//default, /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-depth_first_search/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_depth_first_searchRepair_cardumen(QuixBugsRepairTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
  <testcase name="test_lisRepair_tibra" classname="fr.inria.astor.test.repair.QuixBugsRepairTest" time="2.889">
    <error type="java.lang.NullPointerException:">java.lang.NullPointerException: null
	at com.gzoltar.core.GZoltar.run(GZoltar.java:51)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_lisRepair_tibra(QuixBugsRepairTest.java:309)
</error>
    <system-out><![CDATA[command line arguments: [-customengine  fr.inria.astor.approaches.jgenprog.extension.TibraApproach  -package  java_programs  -srcjavafolder  /src  -id  lis  -scope  package  -binjavafolder  /bin  -population  1  -flthreshold  0.0  -seed  1  -stopfirst  TRUE  -loglevel  DEBUG  -srctestfolder  /src  -location  /root/workspace/SpoonLabs/astor/383218747/./examples/quixbugs/lis  -javacompliancelevel  8  -dependencies  /root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar  -parameters  logtestexecution:TRUE:disablelog:TRUE:maxtime:120:loglevel:debug:autocompile:true:gzoltarpackagetonotinstrument:com.google.gson_engine  -mode  custom  -bintestfolder  /bin  -maxgen  1000]
Source folders: []
Source Test folders: []
Original Bin folder does not exist
Original Bin folder does not exist
Compiling original code from [] saved in /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default
-Executing Gzoltar classpath: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default from 0 classes with test cases
Gzoltar fault localization: min susp value parameter: 0.0
Gzoltar run over: /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default , does it exist? false
-gz-Adding classpath: [/root/workspace/SpoonLabs/astor/383218747/./examples/libs/junit-4.4.jar, /root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis//bin//default]
]]></system-out>
    <system-err><![CDATA[java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" (in directory "/root/workspace/SpoonLabs/astor/383218747/./output_astor/AstorMain-lis/bin/default"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.gzoltar.core.agent.Launcher.launch(Launcher.java:66)
	at com.gzoltar.core.GZoltar.launchAgent(GZoltar.java:177)
	at com.gzoltar.core.GZoltar.run(GZoltar.java:48)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:196)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.calculateSuspicious(GZoltarFaultLocalization.java:87)
	at fr.inria.astor.core.faultlocalization.gzoltar.GZoltarFaultLocalization.searchSuspicious(GZoltarFaultLocalization.java:49)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:1270)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:121)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:170)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.astor.test.repair.QuixBugsRepairTest.test_lisRepair_tibra(QuixBugsRepairTest.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
]]></system-err>
  </testcase>
</testsuite>