-------------------------------------------------------------------------------
Test set: org.apache.calcite.test.LatticeTest
-------------------------------------------------------------------------------
Tests run: 38, Failures: 0, Errors: 3, Skipped: 2, Time elapsed: 156.988 s <<< FAILURE! - in org.apache.calcite.test.LatticeTest
testTwoLattices(org.apache.calcite.test.LatticeTest)  Time elapsed: 55.918 s  <<< ERROR!
java.lang.RuntimeException: 
exception while preparing [select s."unit_sales", p."brand_name"
from "foodmart"."sales_fact_1997" as s
join "foodmart"."product" as p using ("product_id")
]
	at org.apache.calcite.test.LatticeTest.testTwoLattices(LatticeTest.java:698)
Caused by: java.lang.RuntimeException: 
while executing SQL [SELECT COUNT(*) AS "C"
FROM (SELECT "t0"."product_class_id"
FROM (SELECT "product_id"
FROM "foodmart"."sales_fact_1997") AS "t"
INNER JOIN ((SELECT "product_class_id"
FROM "foodmart"."product_class") AS "t0"
INNER JOIN (SELECT "product_class_id", "product_id"
FROM "foodmart"."product") AS "t1" ON "t0"."product_class_id" = "t1"."product_class_id") ON "t"."product_id" = "t1"."product_id"
GROUP BY "t0"."product_class_id") AS "t2"]
	at org.apache.calcite.test.LatticeTest.testTwoLattices(LatticeTest.java:698)
Caused by: java.sql.SQLTransactionRollbackException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.testTwoLattices(LatticeTest.java:698)
Caused by: org.hsqldb.HsqlException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.testTwoLattices(LatticeTest.java:698)

testTileAlgorithm2(org.apache.calcite.test.LatticeTest)  Time elapsed: 72.13 s  <<< ERROR!
java.lang.RuntimeException: 
exception while executing [explain plan for select distinct t."the_year", t."quarter"
from "foodmart"."sales_fact_1997" as s
join "foodmart"."time_by_day" as t using ("time_id")
]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm2(LatticeTest.java:435)
Caused by: java.lang.RuntimeException: 
while executing SQL [SELECT COUNT(*) AS "C"
FROM (SELECT "t0"."product_class_id"
FROM (SELECT "product_id"
FROM "foodmart"."sales_fact_1997") AS "t"
INNER JOIN ((SELECT "product_class_id"
FROM "foodmart"."product_class") AS "t0"
INNER JOIN (SELECT "product_class_id", "product_id"
FROM "foodmart"."product") AS "t1" ON "t0"."product_class_id" = "t1"."product_class_id") ON "t"."product_id" = "t1"."product_id"
GROUP BY "t0"."product_class_id") AS "t2"]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm2(LatticeTest.java:435)
Caused by: java.sql.SQLTransactionRollbackException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm2(LatticeTest.java:435)
Caused by: org.hsqldb.HsqlException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm2(LatticeTest.java:435)

testTileAlgorithm(org.apache.calcite.test.LatticeTest)  Time elapsed: 58.743 s  <<< ERROR!
java.lang.RuntimeException: 
exception while executing [explain plan for select distinct t."the_year", t."quarter"
from "foodmart"."sales_fact_1997" as s
join "foodmart"."time_by_day" as t using ("time_id")
]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.lang.RuntimeException: While populating materialization [adhoc, m{4, 16, 17, 27, 31, 37}]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.lang.RuntimeException: 
while executing SQL [SELECT "t"."store_id", "t0"."recyclable_package", "t0"."low_fat", "t1"."the_year", "t1"."quarter", "t2"."product_family", COUNT(*) AS "m0", SUM("t"."store_sales") AS "m1", SUM("t"."unit_sales") AS "m2"
FROM (SELECT "product_id", "time_id", "store_id", "store_sales", "unit_sales"
FROM "foodmart"."sales_fact_1997") AS "t"
INNER JOIN (SELECT "product_class_id", "product_id", "recyclable_package", "low_fat"
FROM "foodmart"."product") AS "t0" ON "t"."product_id" = "t0"."product_id"
INNER JOIN (SELECT "time_id", "the_year", "quarter"
FROM "foodmart"."time_by_day") AS "t1" ON "t"."time_id" = "t1"."time_id"
INNER JOIN (SELECT "product_class_id", "product_family"
FROM "foodmart"."product_class") AS "t2" ON "t0"."product_class_id" = "t2"."product_class_id"
GROUP BY "t"."store_id", "t0"."recyclable_package", "t0"."low_fat", "t1"."the_year", "t1"."quarter", "t2"."product_family"]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.sql.SQLTransactionRollbackException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: org.hsqldb.HsqlException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)

